### ISSUE TITLE
KeyError: 'nf0'

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineko#10]
I'm trying to generate an FK table to test the performance of https://github.com/N3PDF/pineappl/pull/103. However, when I run `./run.py`, I get the following error message:

```
Traceback (most recent call last):
  File "/scratch/cschwan/pineko/./run.py", line 58, in <module>
    ensure_eko(pineappl_path, myoperator_path)
  File "/scratch/cschwan/pineko/./run.py", line 37, in ensure_eko
    ops = eko.run_dglap(theory_card=theory_card, operators_card=operators_card)
  File "/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/eko/__init__.py", line 27, in run_dglap
    r = runner.Runner(theory_card, operators_card)
  File "/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/eko/runner.py", line 84, in __init__
    tc = ThresholdsAtlas.from_dict(theory_card)
  File "/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/eko/thresholds.py", line 179, in from_dict
    nf_ref = theory_card["nf0"]
KeyError: 'nf0'
```

**Comment by AleCandido** [comment]
Most likely you are using an old version of `eko`

**Comment by felixhekhorn** [comment]
No, most likely you're using an old version of the theory card

**Comment by AleCandido** [comment]
I've to correct myself: the `eko` version is new, but it's somehow fed by old data.

`nf0` is a recent (months) addition to the theory card, and somehow is fed with an old one.

**Comment by AleCandido** [comment]
Confirmed: theories in [`data`](https://github.com/N3PDF/pineko/tree/main/data) are at least 3 months old. The recent `eko` release broke compatibility with them.

**Comment by cschwan** [comment]
Can you please update them, or tell me how to otherwise generate an FK table?

**Comment by AleCandido** [comment]
Yes, definitely.

@felixhekhorn can you confirm we have to add these three lines?
https://github.com/NNPDF/runcards/blob/500e06c14cf2b42c2897fd6360fc0df347af6516/theories/theory_200_1.yaml#L41-L43

**Comment by AleCandido** [comment]
Updated in 4ef8f48597f6e79f907a2227c0329c0aeed2dc7c, @cschwan please check if it's now working

**Comment by cschwan** [comment]
That worked, but now I get:

```
/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/eko/output.py:144: UserWarning: The new targetgrid is close to the current targetgrid
  warnings.warn("The new targetgrid is close to the current targetgrid")
┌───────────────┐
│ Computing ... │
└───────────────┘
   /scratch/cschwan/pineko/data/ATLAS_TTB_8TEV_TOT.pineappl.lz4
 + /scratch/cschwan/pineko/data/myoperator.ATLAS_TTB_8TEV_TOT.pineappl.yaml
 = /scratch/cschwan/pineko/data/myfktable.ATLAS_TTB_8TEV_TOT.pineappl.pineappl
Traceback (most recent call last):
  File "/scratch/cschwan/pineko/./run.py", line 63, in <module>
    convolute(pineappl_path, myoperator_path, myfktable_path, "NNPDF40_nlo_as_01180")
  File "/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/pineko/__init__.py", line 107, in convolute
    operators = eko.output.Output.load_tar(eko_path)
  File "/home/cschwan/projects/pineappl/pineappl_py/env/lib/python3.9/site-packages/eko/output.py", line 490, in load_tar
    raise ValueError(f"'{tarname}' is not a valid tar filename, wrong suffix")
ValueError: '/scratch/cschwan/pineko/data/myoperator.ATLAS_TTB_8TEV_TOT.pineappl.yaml' is not a valid tar filename, wrong suffix
```

**Comment by AleCandido** [comment]
Even `eko` output changed in the meanwhile. Better said: we support a new output format (that is condensed in a tar folder, thus `load_tar`), but you can also still use the old one.

So, either you replace `load_tar` by `load_yaml_from_file`, or you regenerate the operator and use `dump_tar` instead of `dump_yaml_to_file`.

**Comment by cschwan** [comment]
I also had to change the filename, otherwise complains that `.yaml` isn't a fileending for a tar file. Commit 373f5522069d9d95ecb362b73ef1e23357071fd7 fixes these problems.
