### ISSUE TITLE
Do actual `optimize`

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineko#13]
While `optimize` *is* called here https://github.com/N3PDF/pineko/blob/ee6b9da3e7ed6078f2816543cf3952399beaba04/src/pineko/evolve.py#L112 it is currently called with it's default value `def optimize(self, assumptions = "Nf6Ind"):` see https://github.com/N3PDF/pineappl/blob/101cbdefdd3b9f6c0427de48e57bca53e0f3f843/pineappl_py/pineappl/fk_table.py#L37

instead we should add a field to the theory card and use that value

**Comment by AleCandido** [comment]
Available in a moment with the `pineappl` upgrade to v0.5.2

**Comment by cschwan** [comment]
Here you go: https://pypi.org/project/pineappl/0.5.2/

**Comment by AleCandido** [comment]
@felixhekhorn @andreab1997 if you start replacing compatibility layer, take this into account.

**Comment by AleCandido** [comment]
@felixhekhorn @andreab1997 what is missing here?

**Comment by felixhekhorn** [comment]
Nothing - but time :upside_down_face: ; maybe @andreab1997 you can take care of this?

**Comment by andreab1997** [comment]
> Nothing - but time 🙃 ; maybe @andreab1997 you can take care of this?

Yes, of course

**Comment by andreab1997** [comment]
Only to be sure I have understood, we want to add an argument to the theory card (called something like `assumptions`) and use that value as second argument of the function `optimize` instead of using its default value, right?

**Comment by AleCandido** [comment]
But let's start here the "compatibility" project.

This argument was not present before, but we can infer from:
- Q0
- thresholds (matching scales)
- IC

At some point we'll further change (e.g. an ICV, or similar, will appear, at which point might be easier to directly go for assumptions), but let's assume an adiabatic approximation: everything is as it has been for the past few years, changes will be applied on top.

**Comment by andreab1997** [comment]
Do we want to close this issue now that the PR #22 has been merged?

**Comment by felixhekhorn** [comment]
yes
