### ISSUE TITLE
FONLL-B DIS FK table need different PTO

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineko#26]
I'm sorry to say again, but NLO FK tables are still wrong (only FK tables this time though - so it's not expensive):
https://github.com/N3PDF/pineko/blob/e12c6482a32c7c8f902bfa2d2504e4bfe451fd19/src/pineko/theory.py#L325

this is wrong in the case of NLO (so `PTO=1`) and FONLL-B because FONLL-B also contains bits at $O(a_s^2)$ which will be neglected with this statement ...

the solution is
- find out (from the theory card) whether we're in FONLL-B
- check whether we're looking at a DIS grid (from the lumi, I guess - we can cross check with https://github.com/NNPDF/nnpdf/pull/1529)
- eventually do a correction of `max_as`

**Comment by felixhekhorn** [comment]
- if this is done - close it
- did you compare you're `is_dis` determination against https://github.com/NNPDF/nnpdf/pull/1578 ?
- actually https://github.com/N3PDF/pineko/blob/aa1a068edffc75d8ee1a4ed8e5c44fd8630963e1/src/pineko/check.py#L87 it might be a good idea to not rely on the fact that the lepton is always the second particle in the lumi

**Comment by andreab1997** [comment]
Should we close this? @felixhekhorn @AleCandido
