### ISSUE TITLE
SV check does not take into account the PTO

### ISSUE THREAD

**Issue by andreab1997** [N3PDF/pineko#32]
Currently our SV check does not take into account the fact that renormalization sv only start at NLO where NLO actually means next with respect to the first non-zero order of the process. 
Therefore, it does not allow the computation of a sv Fktable for DIS when PTO=1 (which in DIS case is the first non-zero order).

**Comment by andreab1997** [comment]
Can this be closed?

**Comment by felixhekhorn** [comment]
decide yourself :upside_down_face:

**Comment by andreab1997** [comment]
> decide yourself 🙃

Then let's wait to have the full check. At least we won't forget :)

**Comment by felixhekhorn** [comment]
> Can this be closed?

@andreab1997 now?
