### ISSUE TITLE
Grids used for new theories are ordered in the wrong way

### ISSUE THREAD

**Issue by andreab1997** [N3PDF/pineko#38]
with the help of @scarlehoff, I found the problem of the new theories. Doing for example `pineappl convolute BCDMS_NC_EM_D_F2.pineappl.lz4 NNPDF40_nnlo_as_01180` for both the grids used for theory 405 (theory 4 in dom) and theory 424 (theory 24 in dom) what you get is 

```
bin     Q2           x          F2d      scale uncertainty
---+-----+-----+-----+-----+------------+--------+--------
  0  8.75  8.75  0.07  0.07 3.8331501e-1  -10.65%    5.72%
  1 10.25 10.25  0.07  0.07 3.8615391e-1   -7.25%    5.42%
  2 10.25 10.25   0.1   0.1 3.6238832e-1   -6.00%    3.72%
  3 11.75 11.75   0.1   0.1 3.6313899e-1   -5.42%    3.55%
  4 11.75 11.75  0.14  0.14 3.3887777e-1   -4.40%    1.97%
  5 11.75 11.75  0.18  0.18 3.1553538e-1   -3.66%    1.25%
  6 11.75 11.75 0.225 0.225 2.8649654e-1   -2.97%    2.22%
  7 13.25 13.25   0.1   0.1 3.6377078e-1   -5.18%    3.40%
  8 13.25 13.25  0.14  0.14 3.3826829e-1   -4.19%    1.89%
  9 13.25 13.25  0.18  0.18 3.1408120e-1   -3.47%    1.18%
 10 13.25 13.25 0.225 0.225 2.8441184e-1   -2.80%    2.11%
```

```
bin     Q2           x          F2d      scale uncertainty
---+-----+-----+-----+-----+------------+--------+--------
  0  8.75  8.75  0.07  0.07 3.7227338e-1  -11.74%    5.16%
  1 10.25 10.25  0.07  0.07 3.7563029e-1  -10.90%    4.83%
  2 10.25 10.25   0.1   0.1 3.5371954e-1  -10.01%    4.38%
  3 11.75 11.75   0.1   0.1 3.5478369e-1   -9.34%    4.16%
  4 13.25 13.25   0.1   0.1 3.5576112e-1   -8.75%    3.96%
  5 11.75 11.75  0.14  0.14 3.3177244e-1   -8.04%    5.73%
  6 13.25 13.25  0.14  0.14 3.3149059e-1   -7.52%    5.51%
  7    15    15  0.14  0.14 3.3118411e-1   -7.02%    5.29%
  8    17    17  0.14  0.14 3.3076224e-1   -6.59%    5.09%
  9    19    19  0.14  0.14 3.3045852e-1   -6.21%    4.92%
 10 11.75 11.75  0.18  0.18 3.0924455e-1   -6.60%    7.35%
```

So, as you can see, while the grid for theory 424 is ordered by q2 (and this is the correct way since the commondata are ordered in the same way), the gird for theory 405 is ordered by x value. This problem then propagates to the FKs and then to the predictions causing the problems we have seen. 
@felixhekhorn @AleCandido @cschwan Do you have some idea on why the two grids are ordered in different ways? Maybe something is changed in the runcards (?)

**Comment by cschwan** [comment]
> @felixhekhorn @AleCandido @cschwan Do you have some idea on why the two grids are ordered in different ways? Maybe something is changed in the runcards (?)

I would guess that to be the explanation, because the runcards determine the ordering.

**Comment by andreab1997** [comment]
Moreover, we also checked that the problem I had with the cuts is also related to this grid problem. In fact if you do for example `pineappl convolute NMC_NC_EM_P_SIGMARED.pineappl.lz4 NNPDF40_nnlo_as_01180` again for both the grids used for theory 405 (theory 4 in dom) and theory 424 (theory 24 in dom) what you get is that the former has 148 points while the latter has (correctly) 292 points. This of course is a problem with the cuts. (just to be precise: for the moment this seems to be a problem only for "NMC" and the two "CHORUS" but it could well be a problem for other datasets just less pronounced)

**Comment by andreab1997** [comment]
> > @felixhekhorn @AleCandido @cschwan Do you have some idea on why the two grids are ordered in different ways? Maybe something is changed in the runcards (?)
> 
> I would guess that to be the explanation, because the runcards determine the ordering.

Yeah, that was our guess. If this is the case we probably need to regenerate those grids.

**Comment by scarlehoff** [comment]
Actually, I just noticed there is a commit in the runcards repository with "fixing sorting" for this exact dataset https://github.com/NNPDF/runcards/commit/8293f70278ea4224948371cb0a3823688abb1fbd

So maybe the runcards now are correct (and the grids in dom are old) or the new sorting is actually wrong.

**Comment by cschwan** [comment]
I suppose this is a problem when comparing the measurements with the predictions? In that case one should check explicitly that the ordering is correct to avoid that mistake in the future.

**Comment by andreab1997** [comment]
> Actually, I just noticed there is a commit in the runcards repository with "fixing sorting" for this exact set of datasets [NNPDF/runcards@8293f70](https://github.com/NNPDF/runcards/commit/8293f70278ea4224948371cb0a3823688abb1fbd)
> 
> So maybe the runcards now are correct (and the grids in dom are old) or the new sorting is actually wrong.

But actually, since the grids are always the same (for NLO and NNLO) I can just use the ones in theory_424. There is no need to regenerate them since we know that the theory_424 ones are correct. I don't know if I need to regenerate the ekos tho

**Comment by scarlehoff** [comment]
For hadronic yes, for DIS processes the grids for NLO and NNLO are actually different.

**Comment by andreab1997** [comment]
> For hadronic yes, for DIS processes the grids for NLO and NNLO are actually different.

Ok so we really need to regenerate them I guess

**Comment by scarlehoff** [comment]
> But pineko is probably the wrong place.

Sadly issues can not be transferred between organizations.

Anyway, let's wait for @felixhekhorn and @AleCandido to chime in, just to understand whether it is really just a question of regenerating the grids.

**Comment by felixhekhorn** [comment]
> I suppose this is a problem when comparing the measurements with the predictions? In that case one should check explicitly that the ordering is correct to avoid that mistake in the future. But pineko is probably the wrong place.

indeed - back then the problem was that yadism was reshuffling the order given by the experimental data; new FK tables of course contain all meta data from the grid, so esp. the bin information/ordering, but does the experimental data do as well?

**Comment by andreab1997** [comment]
> > Actually, I just noticed there is a commit in the runcards repository with "fixing sorting" for this exact set of datasets [NNPDF/runcards@8293f70](https://github.com/NNPDF/runcards/commit/8293f70278ea4224948371cb0a3823688abb1fbd)
> > So maybe the runcards now are correct (and the grids in dom are old) or the new sorting is actually wrong.
> 
> indeed - this sounds very much like this bug
> 
> * is there a way we can find out when/with which version they have been generated?
> * is this behaviour still present with the current version of runcards?
> 
> (I believe the corresponding yadism commits are [N3PDF/yadism@534a108](https://github.com/N3PDF/yadism/commit/534a1088495b60ced5cd4a8f38b959c192b3b36e) and [N3PDF/yadism@2e89469](https://github.com/N3PDF/yadism/commit/2e89469e764c38ae9ced232a4d01e1c9197280bd) )

I can answer the first question for the moment. Yes we can. Loading the grid with pineappl and then doing `my_grid.raw.key_values()['yadism_version']`. Doing that it seems that, respectively for theory 424 and theory 404:

- yadism versions are the same (`0.10.8`)
- pineappl_gitversion are different (`v0.5.0-4-ga5e91e0` for theory 424 and `v0.5.0-12-g4dbc8cc` for theory 404)
- runcard_gitversion are different (`8293f70` for theory 424 and `cf3e497` for theory 404)
If you wish I can also post the runcard itself but as far as I can see there is nothing interesting there.

**Comment by felixhekhorn** [comment]
> * runcard_gitversion are different (`8293f70` for theory 424 and `cf3e497` for theory 404)

Mmm both of these commits are behind the fix ...

>   If you wish I can also post the runcard itself but as far as I can see there is nothing interesting there.

well, the interesting thing is exactly whether those two are the same and whether they have the same order as the experimental data

PS: there should be no need to use `.raw` - just `my_grid.key_values()` should be fine ... (its the [usual nesting](https://pineappl.readthedocs.io/en/latest/implementation.html))

**Comment by andreab1997** [comment]
This is the theory_404 one
{"PolarizationDIS": 0.0, "ProjectileDIS": "electron", "PropagatorCorrection": 0.0, "TargetDIS": "isoscalar", "interpolation_is_log": true, "interpolation_polynomial_degree": 4, "interpolation_xgrid": [1.9999999999999954e-07, 3.034304765867952e-07, 4.6035014748963906e-07, 6.984208530700364e-07, 1.0596094959101024e-06, 1.607585498470808e-06, 2.438943292891682e-06, 3.7002272069854957e-06, 5.613757716930151e-06, 8.516806677573355e-06, 1.292101569074731e-05, 1.9602505002391748e-05, 2.97384953722449e-05, 4.511438394964044e-05, 6.843744918967896e-05, 0.00010381172986576898, 0.00015745605600841445, 0.00023878782918561914, 0.00036205449638139736, 0.0005487795323670796, 0.0008314068836488144, 0.0012586797144272762, 0.0019034634022867384, 0.0028738675812817515, 0.004328500638820811, 0.006496206194633799, 0.009699159574043398, 0.014375068581090129, 0.02108918668378717, 0.030521584007828916, 0.04341491741702269, 0.060480028754447364, 0.08228122126204893, 0.10914375746330703, 0.14112080644440345, 0.17802566042569432, 0.2195041265003886, 0.2651137041582823, 0.31438740076927585, 0.3668753186482242, 0.4221667753589648, 0.4798989029610255, 0.5397572337880445, 0.601472197967335, 0.6648139482473823, 0.7295868442414312, 0.7956242522922756, 0.8627839323906108, 0.9309440808717544, 1], "observables": {"F2_total": [{"Q2": 8.75, "x": 0.07, "y": 0.5666}, {"Q2": 10.25, "x": 0.07, "y": 0.6637}, {"Q2": 10.25, "x": 0.1, "y": 0.4646}, {"Q2": 11.75, "x": 0.1, "y": 0.5326}, {"Q2": 11.75, "x": 0.14, "y": 0.3804}, {"Q2": 11.75, "x": 0.18, "y": 0.2959}, {"Q2": 11.75, "x": 0.225, "y": 0.2367}, {"Q2": 13.25, "x": 0.1, "y": 0.6006}, {"Q2": 13.25, "x": 0.14, "y": 0.429}, {"Q2": 13.25, "x": 0.18, "y": 0.3337}, {"Q2": 13.25, "x": 0.225, "y": 0.2669}, {"Q2": 13.25, "x": 0.275, "y": 0.2184}, {"Q2": 13.25, "x": 0.35, "y": 0.1716}, {"Q2": 13.25, "x": 0.45, "y": 0.1335}, {"Q2": 15.0, "x": 0.14, "y": 0.4856}, {"Q2": 15.0, "x": 0.18, "y": 0.3777}, {"Q2": 15.0, "x": 0.225, "y": 0.3022}, {"Q2": 15.0, "x": 0.275, "y": 0.2472}, {"Q2": 15.0, "x": 0.35, "y": 0.1943}, {"Q2": 15.0, "x": 0.45, "y": 0.1511}, {"Q2": 15.0, "x": 0.55, "y": 0.1236}, {"Q2": 17.0, "x": 0.07, "y": 0.6598}, {"Q2": 17.0, "x": 0.14, "y": 0.5504001}, {"Q2": 17.0, "x": 0.18, "y": 0.4281}, {"Q2": 17.0, "x": 0.225, "y": 0.3425}, {"Q2": 17.0, "x": 0.275, "y": 0.2802}, {"Q2": 17.0, "x": 0.35, "y": 0.2202}, {"Q2": 17.0, "x": 0.45, "y": 0.1712}, {"Q2": 17.0, "x": 0.55, "y": 0.1401}, {"Q2": 17.0, "x": 0.65, "y": 0.1185}, {"Q2": 19.0, "x": 0.07, "y": 0.7374001}, {"Q2": 19.0, "x": 0.1, "y": 0.5162001}, {"Q2": 19.0, "x": 0.14, "y": 0.6152}, {"Q2": 19.0, "x": 0.18, "y": 0.4785}, {"Q2": 19.0, "x": 0.225, "y": 0.3828}, {"Q2": 19.0, "x": 0.275, "y": 0.3132}, {"Q2": 19.0, "x": 0.35, "y": 0.2461}, {"Q2": 19.0, "x": 0.45, "y": 0.1914}, {"Q2": 19.0, "x": 0.55, "y": 0.1566}, {"Q2": 19.0, "x": 0.65, "y": 0.1325}, {"Q2": 21.5, "x": 0.1, "y": 0.5841}, {"Q2": 21.5, "x": 0.14, "y": 0.4172}, {"Q2": 21.5, "x": 0.18, "y": 0.3245}, {"Q2": 21.5, "x": 0.18, "y": 0.5414001}, {"Q2": 21.5, "x": 0.225, "y": 0.4331}, {"Q2": 21.5, "x": 0.275, "y": 0.3544}, {"Q2": 21.5, "x": 0.35, "y": 0.2784}, {"Q2": 21.5, "x": 0.45, "y": 0.2166}, {"Q2": 21.5, "x": 0.55, "y": 0.1772}, {"Q2": 21.5, "x": 0.65, "y": 0.1499}, {"Q2": 24.5, "x": 0.1, "y": 0.6656}, {"Q2": 24.5, "x": 0.14, "y": 0.4755}, {"Q2": 24.5, "x": 0.18, "y": 0.3698}, {"Q2": 24.5, "x": 0.18, "y": 0.617}, {"Q2": 24.5, "x": 0.225, "y": 0.4936}, {"Q2": 24.5, "x": 0.275, "y": 0.4038}, {"Q2": 24.5, "x": 0.35, "y": 0.3173}, {"Q2": 24.5, "x": 0.45, "y": 0.2468}, {"Q2": 24.5, "x": 0.55, "y": 0.2019}, {"Q2": 24.5, "x": 0.65, "y": 0.1708}, {"Q2": 28.0, "x": 0.14, "y": 0.5434}, {"Q2": 28.0, "x": 0.18, "y": 0.4226}, {"Q2": 28.0, "x": 0.225, "y": 0.3381}, {"Q2": 28.0, "x": 0.225, "y": 0.5641}, {"Q2": 28.0, "x": 0.275, "y": 0.2766}, {"Q2": 28.0, "x": 0.275, "y": 0.4615}, {"Q2": 28.0, "x": 0.35, "y": 0.3626}, {"Q2": 28.0, "x": 0.45, "y": 0.282}, {"Q2": 28.0, "x": 0.55, "y": 0.2308}, {"Q2": 28.0, "x": 0.65, "y": 0.1953}, {"Q2": 32.5, "x": 0.1, "y": 0.6281}, {"Q2": 32.5, "x": 0.14, "y": 0.6307001}, {"Q2": 32.5, "x": 0.18, "y": 0.4905}, {"Q2": 32.5, "x": 0.225, "y": 0.3924}, {"Q2": 32.5, "x": 0.225, "y": 0.6547}, {"Q2": 32.5, "x": 0.275, "y": 0.3211}, {"Q2": 32.5, "x": 0.275, "y": 0.5357}, {"Q2": 32.5, "x": 0.35, "y": 0.2523}, {"Q2": 32.5, "x": 0.35, "y": 0.4209}, {"Q2": 32.5, "x": 0.45, "y": 0.1962}, {"Q2": 32.5, "x": 0.45, "y": 0.3274}, {"Q2": 32.5, "x": 0.55, "y": 0.1605}, {"Q2": 32.5, "x": 0.55, "y": 0.2678}, {"Q2": 32.5, "x": 0.65, "y": 0.1358}, {"Q2": 32.5, "x": 0.65, "y": 0.2266}, {"Q2": 32.5, "x": 0.75, "y": 0.1964}, {"Q2": 37.5, "x": 0.1, "y": 0.7248001}, {"Q2": 37.5, "x": 0.14, "y": 0.5177}, {"Q2": 37.5, "x": 0.18, "y": 0.4027}, {"Q2": 37.5, "x": 0.18, "y": 0.566}, {"Q2": 37.5, "x": 0.225, "y": 0.3221}, {"Q2": 37.5, "x": 0.225, "y": 0.4528}, {"Q2": 37.5, "x": 0.275, "y": 0.2636}, {"Q2": 37.5, "x": 0.275, "y": 0.3705}, {"Q2": 37.5, "x": 0.275, "y": 0.6181}, {"Q2": 37.5, "x": 0.35, "y": 0.2911}, {"Q2": 37.5, "x": 0.35, "y": 0.4856}, {"Q2": 37.5, "x": 0.45, "y": 0.2264}, {"Q2": 37.5, "x": 0.45, "y": 0.3777}, {"Q2": 37.5, "x": 0.55, "y": 0.1852}, {"Q2": 37.5, "x": 0.55, "y": 0.309}, {"Q2": 37.5, "x": 0.65, "y": 0.1567}, {"Q2": 37.5, "x": 0.65, "y": 0.2615}, {"Q2": 37.5, "x": 0.75, "y": 0.2266}, {"Q2": 43.0, "x": 0.14, "y": 0.5936}, {"Q2": 43.0, "x": 0.18, "y": 0.4617}, {"Q2": 43.0, "x": 0.18, "y": 0.649}, {"Q2": 43.0, "x": 0.225, "y": 0.3694}, {"Q2": 43.0, "x": 0.225, "y": 0.5192}, {"Q2": 43.0, "x": 0.275, "y": 0.3022}, {"Q2": 43.0, "x": 0.275, "y": 0.4248}, {"Q2": 43.0, "x": 0.275, "y": 0.7088}, {"Q2": 43.0, "x": 0.35, "y": 0.2375}, {"Q2": 43.0, "x": 0.35, "y": 0.3338}, {"Q2": 43.0, "x": 0.35, "y": 0.5569}, {"Q2": 43.0, "x": 0.45, "y": 0.1847}, {"Q2": 43.0, "x": 0.45, "y": 0.2596}, {"Q2": 43.0, "x": 0.45, "y": 0.4331}, {"Q2": 43.0, "x": 0.55, "y": 0.1511}, {"Q2": 43.0, "x": 0.55, "y": 0.2124}, {"Q2": 43.0, "x": 0.55, "y": 0.3544}, {"Q2": 43.0, "x": 0.65, "y": 0.1797}, {"Q2": 43.0, "x": 0.65, "y": 0.2999}, {"Q2": 43.0, "x": 0.75, "y": 0.1558}, {"Q2": 43.0, "x": 0.75, "y": 0.2599}, {"Q2": 49.5, "x": 0.14, "y": 0.6834}, {"Q2": 49.5, "x": 0.18, "y": 0.5315}, {"Q2": 49.5, "x": 0.225, "y": 0.4252}, {"Q2": 49.5, "x": 0.225, "y": 0.5977001}, {"Q2": 49.5, "x": 0.275, "y": 0.3479}, {"Q2": 49.5, "x": 0.275, "y": 0.489}, {"Q2": 49.5, "x": 0.35, "y": 0.2733}, {"Q2": 49.5, "x": 0.35, "y": 0.3842}, {"Q2": 49.5, "x": 0.35, "y": 0.6411}, {"Q2": 49.5, "x": 0.45, "y": 0.2126}, {"Q2": 49.5, "x": 0.45, "y": 0.2989}, {"Q2": 49.5, "x": 0.45, "y": 0.4986}, {"Q2": 49.5, "x": 0.55, "y": 0.1739}, {"Q2": 49.5, "x": 0.55, "y": 0.2445}, {"Q2": 49.5, "x": 0.55, "y": 0.4079}, {"Q2": 49.5, "x": 0.65, "y": 0.1472}, {"Q2": 49.5, "x": 0.65, "y": 0.2069}, {"Q2": 49.5, "x": 0.65, "y": 0.3452}, {"Q2": 49.5, "x": 0.75, "y": 0.1793}, {"Q2": 49.5, "x": 0.75, "y": 0.2992}, {"Q2": 57.0, "x": 0.14, "y": 0.7869}, {"Q2": 57.0, "x": 0.18, "y": 0.612}, {"Q2": 57.0, "x": 0.225, "y": 0.4896}, {"Q2": 57.0, "x": 0.225, "y": 0.6883}, {"Q2": 57.0, "x": 0.275, "y": 0.4006}, {"Q2": 57.0, "x": 0.275, "y": 0.5631}, {"Q2": 57.0, "x": 0.35, "y": 0.3148}, {"Q2": 57.0, "x": 0.35, "y": 0.4425}, {"Q2": 57.0, "x": 0.35, "y": 0.7382001}, {"Q2": 57.0, "x": 0.45, "y": 0.2448}, {"Q2": 57.0, "x": 0.45, "y": 0.3441}, {"Q2": 57.0, "x": 0.45, "y": 0.5741}, {"Q2": 57.0, "x": 0.55, "y": 0.2003}, {"Q2": 57.0, "x": 0.55, "y": 0.2816}, {"Q2": 57.0, "x": 0.55, "y": 0.4698}, {"Q2": 57.0, "x": 0.65, "y": 0.1695}, {"Q2": 57.0, "x": 0.65, "y": 0.2382}, {"Q2": 57.0, "x": 0.65, "y": 0.3975}, {"Q2": 57.0, "x": 0.75, "y": 0.1469}, {"Q2": 57.0, "x": 0.75, "y": 0.2065}, {"Q2": 57.0, "x": 0.75, "y": 0.3445}, {"Q2": 65.5, "x": 0.18, "y": 0.7033}, {"Q2": 65.5, "x": 0.225, "y": 0.5626}, {"Q2": 65.5, "x": 0.275, "y": 0.4603}, {"Q2": 65.5, "x": 0.275, "y": 0.6471}, {"Q2": 65.5, "x": 0.35, "y": 0.3617}, {"Q2": 65.5, "x": 0.35, "y": 0.5084}, {"Q2": 65.5, "x": 0.45, "y": 0.2813}, {"Q2": 65.5, "x": 0.45, "y": 0.3955}, {"Q2": 65.5, "x": 0.45, "y": 0.6598}, {"Q2": 65.5, "x": 0.55, "y": 0.2302}, {"Q2": 65.5, "x": 0.55, "y": 0.3236}, {"Q2": 65.5, "x": 0.55, "y": 0.5398}, {"Q2": 65.5, "x": 0.65, "y": 0.1948}, {"Q2": 65.5, "x": 0.65, "y": 0.2738}, {"Q2": 65.5, "x": 0.65, "y": 0.4568}, {"Q2": 65.5, "x": 0.75, "y": 0.1688}, {"Q2": 65.5, "x": 0.75, "y": 0.2373}, {"Q2": 65.5, "x": 0.75, "y": 0.3959}, {"Q2": 75.0, "x": 0.225, "y": 0.6442}, {"Q2": 75.0, "x": 0.275, "y": 0.5271}, {"Q2": 75.0, "x": 0.275, "y": 0.7410001}, {"Q2": 75.0, "x": 0.35, "y": 0.4142}, {"Q2": 75.0, "x": 0.35, "y": 0.5822001}, {"Q2": 75.0, "x": 0.45, "y": 0.3221}, {"Q2": 75.0, "x": 0.45, "y": 0.4528}, {"Q2": 75.0, "x": 0.45, "y": 0.7555}, {"Q2": 75.0, "x": 0.55, "y": 0.2636}, {"Q2": 75.0, "x": 0.55, "y": 0.3705}, {"Q2": 75.0, "x": 0.55, "y": 0.6181}, {"Q2": 75.0, "x": 0.65, "y": 0.223}, {"Q2": 75.0, "x": 0.65, "y": 0.3135}, {"Q2": 75.0, "x": 0.65, "y": 0.523}, {"Q2": 75.0, "x": 0.75, "y": 0.1933}, {"Q2": 75.0, "x": 0.75, "y": 0.2717}, {"Q2": 75.0, "x": 0.75, "y": 0.4533}, {"Q2": 86.0, "x": 0.225, "y": 0.7387}, {"Q2": 86.0, "x": 0.275, "y": 0.6044}, {"Q2": 86.0, "x": 0.35, "y": 0.4749}, {"Q2": 86.0, "x": 0.35, "y": 0.6676}, {"Q2": 86.0, "x": 0.45, "y": 0.3694}, {"Q2": 86.0, "x": 0.45, "y": 0.5192}, {"Q2": 86.0, "x": 0.55, "y": 0.3022}, {"Q2": 86.0, "x": 0.55, "y": 0.4248}, {"Q2": 86.0, "x": 0.55, "y": 0.7088}, {"Q2": 86.0, "x": 0.65, "y": 0.2557}, {"Q2": 86.0, "x": 0.65, "y": 0.3595}, {"Q2": 86.0, "x": 0.65, "y": 0.5997}, {"Q2": 86.0, "x": 0.75, "y": 0.2216}, {"Q2": 86.0, "x": 0.75, "y": 0.3115}, {"Q2": 86.0, "x": 0.75, "y": 0.5198}, {"Q2": 99.0, "x": 0.275, "y": 0.6958}, {"Q2": 99.0, "x": 0.35, "y": 0.5467001}, {"Q2": 99.0, "x": 0.35, "y": 0.7685}, {"Q2": 99.0, "x": 0.45, "y": 0.4252}, {"Q2": 99.0, "x": 0.45, "y": 0.5977001}, {"Q2": 99.0, "x": 0.55, "y": 0.3479}, {"Q2": 99.0, "x": 0.55, "y": 0.489}, {"Q2": 99.0, "x": 0.65, "y": 0.2944}, {"Q2": 99.0, "x": 0.65, "y": 0.4138}, {"Q2": 99.0, "x": 0.65, "y": 0.6904001}, {"Q2": 99.0, "x": 0.75, "y": 0.2551}, {"Q2": 99.0, "x": 0.75, "y": 0.3586}, {"Q2": 99.0, "x": 0.75, "y": 0.5983}, {"Q2": 115.5, "x": 0.275, "y": 0.8117}, {"Q2": 115.5, "x": 0.35, "y": 0.6378}, {"Q2": 115.5, "x": 0.45, "y": 0.4961}, {"Q2": 115.5, "x": 0.45, "y": 0.6973}, {"Q2": 115.5, "x": 0.55, "y": 0.4059}, {"Q2": 115.5, "x": 0.55, "y": 0.5705}, {"Q2": 115.5, "x": 0.65, "y": 0.3434}, {"Q2": 115.5, "x": 0.65, "y": 0.4828}, {"Q2": 115.5, "x": 0.75, "y": 0.2976}, {"Q2": 115.5, "x": 0.75, "y": 0.4184}, {"Q2": 137.5, "x": 0.35, "y": 0.7593001}, {"Q2": 137.5, "x": 0.45, "y": 0.5906}, {"Q2": 137.5, "x": 0.55, "y": 0.4832}, {"Q2": 137.5, "x": 0.55, "y": 0.6792001}, {"Q2": 137.5, "x": 0.65, "y": 0.4088}, {"Q2": 137.5, "x": 0.65, "y": 0.5747001}, {"Q2": 137.5, "x": 0.75, "y": 0.3543}, {"Q2": 137.5, "x": 0.75, "y": 0.4981}, {"Q2": 175.0, "x": 0.45, "y": 0.7516}, {"Q2": 175.0, "x": 0.55, "y": 0.615}, {"Q2": 175.0, "x": 0.65, "y": 0.5204}, {"Q2": 175.0, "x": 0.75, "y": 0.451}, {"Q2": 230.0, "x": 0.55, "y": 0.8082001}, {"Q2": 230.0, "x": 0.65, "y": 0.6839001}, {"Q2": 230.0, "x": 0.75, "y": 0.5927001}]}, "prDIS": "NC"}'

**Comment by andreab1997** [comment]
As you can see the F2total kinematics is ordered by Q2 (for example after the first two with x=0.1 there are a few and then again x=0.1). Instead the right one has the three x=0.1 one which are consecutive

**Comment by scarlehoff** [comment]
>         runcard_gitversion are different (8293f70 for theory 424 and cf3e497 for theory 404)

What is the version for theory 400 instead?

**Comment by andreab1997** [comment]
> >         runcard_gitversion are different (8293f70 for theory 424 and cf3e497 for theory 404)
> 
> What is the version for theory 400 instead? (since that's the correct commit for sure)

It Is the same of theory 424

**Comment by felixhekhorn** [comment]
> * is this behaviour still present with the current version of runcards?

I think this is the relevant question - because it provides an easy fix: recomputation ...

**Comment by andreab1997** [comment]
@cschwan @felixhekhorn @scarlehoff @AleCandido I have good news. It seems that all the problems have been solved once corrected the starting grids. I have recomputed (part of) the fktables and I have runned again the comparison. The results are here if you want to have a look. 
[comparison_208vs405_benchpack.tgz](https://github.com/N3PDF/pineko/files/9241510/comparison_208vs405_benchpack.tgz)

Note that this results have been produced with the new package `benchmark` which is [here](https://github.com/NNPDF/fktables/tree/benchmarks) (not yet merged) with the command `benchmark compare_set /Users/andrea/Downloads/210612-n3fit-data-003.yml 405 208 NNPDF40_nnlo_as_01180 -p comparison_208vs405_benchpack -r 0.05`

**Comment by AleCandido** [comment]
Ok, now it is everything as expected.
E.g. NUTEV is one of the worst. But just above bottom mass, exactly where we expected. Everything else seems to be under control.

Thank you very much :)

**Comment by cschwan** [comment]
@andreab1997 good job! What's the meaning of 'relative tolerance'? I suppose it's an uncertainty, but I'm not sure which one.

**Comment by andreab1997** [comment]
> @andreab1997 good job! What's the meaning of 'relative tolerance'? I suppose it's an uncertainty, but I'm not sure which one.

It is just the tolerance you accept while comparing the two predictions. If you look to the plot you can see that it represents the error bar. In this way you can easily see which points are compatible and which are not .

**Comment by cschwan** [comment]
This I understand, but how do you calculate it?

**Comment by andreab1997** [comment]
> This I understand, but how do you calculate it?

I don't know if I have understood the question but I don't calculate the rtol, it is just an argument. Then, the "uncertainties" on the "old_predictions" (so the ones you are comparing with) are just `old_predictions * rtol` and this is th error bar you see. Have I answered your question or have I misunderstood?

**Comment by cschwan** [comment]
Yes, that's what I asked for. And I suppose the relative tolerance that you assume is simply 5 %?

**Comment by andreab1997** [comment]
> Yes, that's what I asked for. And I suppose the relative tolerance that you assume is simply 5 %?

yes indeed :)

**Comment by andreab1997** [comment]
Since this issue is still open I post here the comparison between the new sv theories (for both schemeB and C) and the old sv theories (163 and related). I believe there still is something fishy happening but maybe I am wrong and the disagreement is just what we want from the new theories. 
[schemeB_comparison.zip](https://github.com/N3PDF/pineko/files/9358381/schemeB_comparison.zip)
[schemeC_comparison.zip](https://github.com/N3PDF/pineko/files/9358385/schemeC_comparison.zip)

**Comment by felixhekhorn** [comment]
If this issue is completed, let's close it - and instead e.g. we can use the wiki to post the comparison

**Comment by andreab1997** [comment]
> If this issue is completed, let's close it - and instead e.g. we can use the wiki to post the comparison

Ok I am closing. Since there is a lot of stuff for the comparison I will open a new wiki page.
