### ISSUE TITLE
FK Spec

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/pineko#7]
## Background
How the fktable is loaded to be used in the fit can be seen [here](https://github.com/NNPDF/nnpdf/blob/c25ef618907da7d57c38bb62a2e904dfccba5056/validphys2/src/validphys/n3fit_data_utils.py#L76). While the actual convolution is performed [here](https://github.com/NNPDF/nnpdf/blob/c25ef618907da7d57c38bb62a2e904dfccba5056/n3fit/src/n3fit/layers/DY.py#L48) and [here](https://github.com/NNPDF/nnpdf/blob/c25ef618907da7d57c38bb62a2e904dfccba5056/n3fit/src/n3fit/layers/Observable.py#L49).
Some variables that I use there and I'm going to use to define the stuff below:
- `ndata`: number of data points
- `nbasis`: number of channels that are different from 0
- `nx`: number of points in the grid in x

## Input
I will ask for the fktable by giving the following information:
```
theoryid: 200
dataset_inputs:
    - {dataset: ATLAS_WZ_TOT_13TEV, cfac: [NRM, QCD]}
```

If you apply the c-factors for me it is much appreciated. Otherwise validphys will do so.
The way it works right now is that validphys checks whether the theoryid exists in `<prefix>/share/NNPDF/data` and if it doesn't it downloads the [json](https://nnpdf.web.cern.ch/nnpdf/tables/theorydata.json) to see whether it exists in the [server](https://nnpdf.web.cern.ch/nnpdf/tables/).

If it exists it downloads the theory and then loops over all datasets opening the file, reading the data, applying the c-factors if needed, etc... 

## Actual specs
Once the theory has been downloaded and opened I need to get the following information:

- `fktable`
A tensor of shape `(ndata, nbasis, nx, nx)` for hadronic processes or `(ndata, nbasis, nx)` for DIS processes.
- `xgrid`
The grid in x. If/when pineapple tables use the same grid for all fktables this can come from somewhere else or be a pointer to some common place.
- `basis`
List of channels that are different from 0. For DIS fits this is a list of PDF flavours like (1, 2, 3, -3) and anything more complicated than that I guess would be silly. For hadronic fits you can decide how to give me the information. The way I use it is by creating a `PDF x PDF = Luminosity` tensor and then masking it with a boolean tensor of size `(flavours, flavours)`.

Then some metadata that would make my life easier (but the information is contained in the objects above):
- `ndata`: number of experimental data points
- `nx`: number of points in the x-grid
- `nbasis`: number of non-zero channels
- `hadronic`: boolean flag telling me whether the process is hadronic or not

Note that I don't put any constraints in the type of the different objects. To actually operate with them I will make them into tensorflow tensors so numpy arrays is the more natural choice but I can work with anything.

## Wishlist
I'm not entirely sure you can compress the current `.dat` files much more than they currently are (I don't know how much effort was put into compressing them back in the day) but it would make me much happier if instead of downloading 3 GB to do a fit I could download just 1.

**Comment by cschwan** [comment]
Concerning the C factors and other factors applied by apfelcomb, I'd like to know what they are used for. I know of the following uses:

1) NNLO QCD and/or NLO EW K factors and
2) to convert between different units: some grids are given femtobarn, or are in picobarn, therefore one had to add a factor 1000 somewhere

Are there more? @scarlehoff @scarrazza 

The use of 1) should IMO be implemented in PineAPPL, see https://github.com/N3PDF/pineappl/issues/7, because I don't like related data in different places. Different units as in 2) are already taken care of by metadata in PineAPPL, where `y_unit` is either `fb` or `pb` (or `pb/GeV`, ...).

**Comment by cschwan** [comment]
@scarlehoff I've had a quick look at the FK tables and saw that they're text files where the numbers are written with the full double precision. PineAPPL grids instead are binary files, and I've made sure that zeros are not stored at all. Overall that makes me quite optimistic about the total size of all PineAPPL FKtables.

**Comment by AleCandido** [comment]
> ## Input
> 
> I will ask for the fktable by giving the following information:
> 
> ```
> theoryid: 200
> dataset_inputs:
>     - {dataset: ATLAS_WZ_TOT_13TEV, cfac: [NRM, QCD]}
> ```

Ok fine, so there will be a dataset database somewhere and `ATLAS_WZ_TOT_13TEV` works like an `id` for it. Then also the pineapplgrids relative to `yadism` will be generated ahead of time (even if they will be quite fast you could generate on the fly).

>     * `ndata`: number of experimental data points
> 
>     * `nx`: number of points in the x-grid
> 
>     * `nbasis`: number of non-zero channels
> 
>     * `hadronic`: boolean flag telling me whether the process is hadronic or not

3 out of 4 can be computed from the previous data (essentially calling `len(ciao)` or  `len(ciao.shape()) == 3)`, nevertheless if it's convenient for you it costs us nothing to provide them as `@property`.

> Note that I don't put any constraints in the type of the different objects. To actually operate with them I will make them into tensorflow tensors so numpy arrays is the more natural choice but I can work with anything.

The only other option it's to provide some raw `rust` structure (i.e. `ndarray` == numrust), but then I would say that the only *reasonable* option it's numpy arrays.

> ## Wishlist
> 
> I'm not entirely sure you can compress the current `.dat` files much more than they currently are (I don't know how much effort was put into compressing them back in the day) but it would make me much happier if instead of downloading 3 GB to do a fit I could download just 1.

We are using pineapplgrids as output format, and to my understanding @cschwan put already a lot of effort in compressing them, so if there was room for further compression they will be compressed, but we'll keep an eye.

**Comment by scarlehoff** [comment]
> 3 out of 4 can be computed from the previous data (essentially calling `len(ciao)` or `len(ciao.shape()) == 3)`, nevertheless if it's convenient for you it costs us nothing to provide them as `@property`.

All of them. If the basis is rank-2 then it is hadronic. This just makes my life easier. Mainly I won't have to remember whether the first dimension of the fktable is the `ndata` or the `nx`.

**Comment by AleCandido** [comment]
> All of them. If the basis is rank-2 then it is hadronic. This just makes my life easier. Mainly I won't have to remember whether the first dimension of the fktable is the `ndata` or the `nx`.

I was wondering just about the `nbasis` since you said *nonzero elements*, but then I realized it was one of the dimensions of the array. Then yes: all will be provided as `@property`.

**Comment by felixhekhorn** [comment]
I think @scarlehoff you're happy with the current layout in `pineappl_py`, right? Please reopen if you don't agree
