### ISSUE TITLE
Check available ekos

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/pineko#9]
At this point we start having a few ekos computed, and as we found out with @felixhekhorn computing one of them is quite an expensive task (at least for development, since it's blocking us).

Moreover, I believe that a few eko can really be recycled, e.g. I think that most of LHC pineapplgrids will have the same `x_grid` and `Q2_grid`.

However it is a bit annoying to check which one of the available ekos is the correct one, but we have all the tools required to automatize the process.

#### Proposal
Let's make a trivial function (and maybe provide a subcommand) that given a folder explore the files inside (or even all the files in the tree) for ekos, and output all the compatible ones that has been found.

#### Note
This is a step forward towards the toolchain automation and assets management. I'm considering that maybe we'll simply need to progressively improve tasks that we're doing manually at the moment, instead of projecting an actual automation pipeline all-together.

**Comment by AleCandido** [comment]
I guess this outdated enough, and superseded by #12 in any case. Is it correct @felixhekhorn?

**Comment by felixhekhorn** [comment]
- actually this functionality was implemented in `fkutils`: https://github.com/NNPDF/fktables/blob/8ce3969fe05316c33780d5227981c712982bb36c/fkutils/builder.py#L191
- however, I did not port it here - again relying on https://github.com/N3PDF/eko/issues/96
